@author Nassir Mohammad

# Preliminaries

In [1]:
import os
import sys 
sys.path.append('../')
sys.path.append('../scripts')

import warnings
from perception_nassir import Perception

import dataframe_image as dfi

import numpy as np
import pandas as pd

from scripts.utilities import apply_classifiers
from scripts.utilities import get_file_data

from sklearn.preprocessing import StandardScaler
from rendering_functions import highlight_max, highlight_min

image_save_path = ''
image_save_switch = False

# Paper 1 datasets

In [2]:
# make table for dataset, # dimensions, # samples, # percentage of anomalies

base_path = "../data/ODDS_multivariate/"
data_properties_df = None

# loop over datasets in directory
for file_name in os.listdir(base_path):

    dataset_name, X_original, y = get_file_data(base_path, file_name)

    if dataset_name is None:
        continue

    # write dataset summary to dataframe
    data_properties_temp = pd.DataFrame({
        'Name': [dataset_name],
        '\# examples': [X_original.shape[0]],
        '\# features': [X_original.shape[1]],
        # '# anomalies': [y.sum()],
        '\% anomalies': [float(np.round(y.sum()/X_original.shape[0]*100, 2))],
    })

    data_properties_df = pd.concat(
        [data_properties_df, data_properties_temp]).reset_index(drop=True)

In [3]:
img_title = "Dataset properties"
path_save = image_save_path + "dataset_properties.png"

# order the dataset rows by name
data_properties_df = data_properties_df.sort_values(by=['Name']).reset_index(drop=True)

data_properties_df_styled = data_properties_df.style.format({'\% anomalies': "{:.2f}"}).hide()

#data_properties_df_styled = data_properties_df.style.hide_index()

#dfi.export(data_properties_df,path_save)

data_properties_df_styled

In [4]:
# file names
# ########################
# file_name = "wbc.mat" 
# file_name = "cardio.mat"
# file_name = "thyroid.mat"
# file_name = "musk.mat"
# file_name = "shuttle.mat"
# file_name = "satimage-2.mat"
# file_name = "http.matv7"
# file_name = "smtp.matv7"
# file_name = "credit-card.csv"

classifiers = [
    'HBOS',  # to be ignored, first run in loop slower
    'HBOS',
    'IForest',
    'KNN',
    'LOF',
    'MCD',
    'OCSVM',
    'Perception',
]

metrics_df = None

with warnings.catch_warnings():
    warnings.simplefilter('ignore')

    # loop over datasets in directory
    for file_name in os.listdir(base_path):

        dataset_name, X_original, y = get_file_data(base_path, file_name)

        if dataset_name is None:
            continue

        # scaling (very important to get right)
        # scale to zero mean and unit standard deviation along each feature
        sc = StandardScaler(with_mean=False)
        sc.fit(X_original)
        X = sc.transform(X_original)

        # Apply each classifier to dataset
        with warnings.catch_warnings():
            warnings.simplefilter('ignore')

            print('current file in progress ...: {}'.format(dataset_name))

            metrics_temp = apply_classifiers(classifiers, dataset_name,
                                             predict_data=X,
                                             predict_labels=y,
                                             train_data=X)

        metrics_df = pd.concat([metrics_df, metrics_temp])

    metrics_df.reset_index(drop=True)

current file in progress ...: credit-card
current classifier in progress: HBOS
total run time: 2.418627542210743
current classifier in progress: HBOS
total run time: 0.765158957336098
current classifier in progress: IForest
total run time: 3.294221875956282
current classifier in progress: KNN
current classifier in progress: LOF
current classifier in progress: MCD
total run time: 43.30430595809594
current classifier in progress: OCSVM
current classifier in progress: Perception
total run time: 0.29077124991454184
current file in progress ...: cardio
current classifier in progress: HBOS
total run time: 0.005209125112742186
current classifier in progress: HBOS
total run time: 0.004532125312834978
current classifier in progress: IForest
total run time: 0.08156112511642277
current classifier in progress: KNN
total run time: 0.2786257080733776
current classifier in progress: LOF
total run time: 0.036602583015337586
current classifier in progress: MCD
total run time: 0.4049022498074919
current classifier in progress: OCSVM
total run time: 0.31299170781858265
current classifier in progress: Perception
total run time: 0.0020091249607503414
current file in progress ...: shuttle
current classifier in progress: HBOS
total run time: 0.04558762488886714
current classifier in progress: HBOS
total run time: 0.039490291848778725
current classifier in progress: IForest
total run time: 0.6488635411951691
current classifier in progress: KNN
total run time: 8.64602895709686
current classifier in progress: LOF
total run time: 12.190615208121017
current classifier in progress: MCD
total run time: 8.813719458179548
current classifier in progress: OCSVM
total run time: 173.19000578997657
current classifier in progress: Perception
total run time: 0.03609845880419016
current file in progress ...: musk
current classifier in progress: HBOS
total run time: 0.053095750976353884
current classifier in progress: HBOS
total run time: 0.05743520916439593
current classifier in progress: IForest
total run time: 0.11469029099680483
current classifier in progress: KNN
total run time: 2.1495570421684533
current classifier in progress: LOF
total run time: 0.10275729093700647
current classifier in progress: MCD
total run time: 25.86721258307807
current classifier in progress: OCSVM
total run time: 1.4868919579312205
current classifier in progress: Perception
total run time: 0.009853876195847988
current file in progress ...: http
current classifier in progress: HBOS
total run time: 0.1467984167393297
current classifier in progress: HBOS
total run time: 0.14650929206982255
current classifier in progress: IForest
total run time: 7.022776083322242
current classifier in progress: KNN
total run time: 46.299881167011335
current classifier in progress: LOF
total run time: 18.688659833045676
current classifier in progress: MCD
total run time: 46.28795783407986
current classifier in progress: OCSVM
current classifier in progress: Perception
total run time: 0.35205029183998704
current file in progress ...: smtp
current classifier in progress: HBOS
total run time: 0.029181126272305846
current classifier in progress: HBOS
total run time: 0.026424583047628403
current classifier in progress: IForest
total run time: 1.2149226230103523
current classifier in progress: KNN
total run time: 6.107878999784589
current classifier in progress: LOF
total run time: 1.695884999120608
current classifier in progress: MCD
total run time: 9.51633191620931
current classifier in progress: OCSVM
total run time: 630.1486367508769
current classifier in progress: Perception
total run time: 0.06713816616684198
current file in progress ...: thyroid
current classifier in progress: HBOS
total run time: 0.00530991586856544
current classifier in progress: HBOS
total run time: 0.002690583933144808
current classifier in progress: IForest
total run time: 0.12628529011271894
current classifier in progress: KNN
total run time: 0.2994724989403039
current classifier in progress: LOF
total run time: 0.15694783278740942
current classifier in progress: MCD
total run time: 0.44168508308939636
current classifier in progress: OCSVM
total run time: 0.9182429579086602
current classifier in progress: Perception
total run time: 0.0026567080058157444
current file in progress ...: wbc
current classifier in progress: HBOS
total run time: 0.0030170828104019165
current classifier in progress: HBOS
total run time: 0.0027334592305123806
current classifier in progress: IForest
total run time: 0.0636969581246376
current classifier in progress: KNN
total run time: 0.034025041153654456
current classifier in progress: LOF
total run time: 0.006844501243904233
current classifier in progress: MCD
total run time: 0.22621912485919893
current classifier in progress: OCSVM
total run time: 0.020445792004466057
current classifier in progress: Perception
total run time: 0.000669501256197691
current file in progress ...: satimage-2
current classifier in progress: HBOS
total run time: 0.01934533310122788
current classifier in progress: HBOS
total run time: 0.019570249132812023
current classifier in progress: IForest
total run time: 0.16478254180401564
current classifier in progress: KNN
total run time: 1.2763081239536405
current classifier in progress: LOF
total run time: 0.29626370780169964
current classifier in progress: MCD
total run time: 12.844287000130862
current classifier in progress: OCSVM
total run time: 3.945772707927972
current classifier in progress: Perception
total run time: 0.006354332901537418

In [5]:
# create dataframe for precision
df_precision = metrics_df[['Dataset', 'Classifier', 'Precision']]
df_precision = pd.pivot_table(df_precision, values = 'Precision', index=['Classifier'], columns='Dataset').reset_index()
df_precision.columns.name = None

cols = [col for col in df_precision.columns]
formatdict = {}
for col in cols: formatdict[col] = "{:.3f}"
formatdict.pop('Classifier', None)

sub = df_precision.columns.values.tolist()
sub.remove('Classifier')
sub

df_precision = df_precision.style.hide().apply(highlight_max, subset=sub).format(formatdict)

# img_title = "Precision results"
# path_save = image_save_path + "dataset_precision.png"

# dfi.export(df_precision,path_save)

df_precision

In [6]:
# create dataframe for recall
df_recall = metrics_df[['Dataset', 'Classifier', 'Recall']]
df_recall = pd.pivot_table(df_recall, values = 'Recall', index=['Classifier'], columns='Dataset').reset_index()
df_recall.columns.name = None

cols = [col for col in df_recall.columns]
formatdict = {}
for col in cols: formatdict[col] = "{:.2f}"
formatdict.pop('Classifier', None)

sub = df_recall.columns.values.tolist()
sub.remove('Classifier')
sub

df_recall = df_recall.style.hide().apply(highlight_max, subset=sub).format(formatdict)

img_title = "Recall results"
path_save = image_save_path + "dataset_recall.png"

# dfi.export(df_recall,path_save)

df_recall

In [7]:
# create dataframe for F1-score
df_f1= metrics_df[['Dataset', 'Classifier', 'F1']]
df_f1 = pd.pivot_table(df_f1, values = 'F1', index=['Classifier'], columns='Dataset').reset_index()
df_f1.columns.name = None

cols = [col for col in df_f1.columns]
formatdict = {}
for col in cols: formatdict[col] = "{:.3f}"
formatdict.pop('Classifier', None)

sub = df_f1.columns.values.tolist()
sub.remove('Classifier')
sub

df_f1 = df_f1.style.hide().apply(highlight_max, subset=sub).format(formatdict)

img_title = "F1-score results"
path_save = image_save_path + "dataset_f1-score.png"

# dfi.export(df_f1,path_save)

df_f1

In [8]:
# create dataframe for Area under ROC curve
df1= metrics_df[['Dataset', 'Classifier', 'AUC']]
df1 = pd.pivot_table(df1, values = 'AUC', index=['Classifier'], columns='Dataset').reset_index()
df1.columns.name = None

cols = [col for col in df1.columns]
formatdict = {}
for col in cols: formatdict[col] = "{:.2f}"
formatdict.pop('Classifier', None)

sub = df1.columns.values.tolist()
sub.remove('Classifier')
sub

df1 = df1.style.hide().apply(highlight_max, subset=sub).format(formatdict)

img_title = "F1-score results"
path_save = image_save_path + "dataset_auc.png"

# dfi.export(df1,path_save)

df1

In [9]:
# create dataframe for total training and prediction time
df1= metrics_df[['Dataset', 'Classifier', 'Runtime']]
df1 = pd.pivot_table(df1, values = 'Runtime', index=['Classifier'], columns='Dataset').reset_index()
df1.columns.name = None

cols = [col for col in df1.columns]
formatdict = {}
for col in cols: formatdict[col] = "{:.4f}"
formatdict.pop('Classifier', None)

sub = df1.columns.values.tolist()
sub.remove('Classifier')
sub

df1 = df1.style.hide().apply(highlight_min, subset=sub).format(formatdict)

path_save = image_save_path + "dataset_total_time.png"

# dfi.export(df1,path_save)

df1