@author Nassir Mohammad

# Preliminaries

In [1]:
import os
import sys 
sys.path.append('../scripts')

import warnings
from PerceptionAlgorithm import Perception

import dataframe_image as dfi

import numpy as np
import pandas as pd

from utilities import apply_classifiers
from utilities import get_file_data

from sklearn.preprocessing import StandardScaler
from rendering_functions import highlight_max, highlight_min

image_save_path = ''
image_save_switch = False

# Paper 1 datasets

In [2]:
# make table for dataset, # dimensions, # samples, # percentage of anomalies

base_path = "../data/ODDS_multivariate/"
data_properties_df = None

# loop over datasets in directory
for file_name in os.listdir(base_path):

    dataset_name, X_original, y = get_file_data(base_path, file_name)

    if dataset_name is None:
        continue

    # write dataset summary to dataframe
    data_properties_temp = pd.DataFrame({
        'Name': [dataset_name],
        '\# examples': [X_original.shape[0]],
        '\# features': [X_original.shape[1]],
        # '# anomalies': [y.sum()],
        '\% anomalies': [float(np.round(y.sum()/X_original.shape[0]*100, 2))],
    })

    data_properties_df = pd.concat(
        [data_properties_df, data_properties_temp]).reset_index(drop=True)

In [3]:
img_title = "Dataset properties"
path_save = image_save_path + "dataset_properties.png"

# order the dataset rows by name
data_properties_df = data_properties_df.sort_values(by=['Name']).reset_index(drop=True)

data_properties_df_styled = data_properties_df.style.format({'\% anomalies': "{:.2f}"}).hide_index()

#data_properties_df_styled = data_properties_df.style.hide_index()

#dfi.export(data_properties_df,path_save)

data_properties_df_styled

In [4]:
# file names
# ########################
# file_name = "wbc.mat" 
# file_name = "cardio.mat"
# file_name = "thyroid.mat"
# file_name = "musk.mat"
# file_name = "shuttle.mat"
# file_name = "satimage-2.mat"
# file_name = "http.matv7"
# file_name = "smtp.matv7"
# file_name = "credit-card.csv"

classifiers = [
    'HBOS',  # to be ignored, first run in loop slower
    'HBOS',
    'IForest',
    'KNN',
    'LOF',
    'MCD',
    'OCSVM',
    'Perception',
]

metrics_df = None

with warnings.catch_warnings():
    warnings.simplefilter('ignore')

    # loop over datasets in directory
    for file_name in os.listdir(base_path):

        dataset_name, X_original, y = get_file_data(base_path, file_name)

        if dataset_name is None:
            continue

        # scaling (very important to get right)
        # scale to zero mean and unit standard deviation along each feature
        sc = StandardScaler(with_mean=False)
        sc.fit(X_original)
        X = sc.transform(X_original)

        # Apply each classifier to dataset
        with warnings.catch_warnings():
            warnings.simplefilter('ignore')

            print('current file in progress ...: {}'.format(dataset_name))

            metrics_temp = apply_classifiers(classifiers, dataset_name,
                                             predict_data=X,
                                             predict_labels=y,
                                             train_data=X)

        metrics_df =\
            pd.concat([metrics_df, metrics_temp])

    metrics_df.reset_index(drop=True)

current file in progress ...: credit-card
current classifier in progress: HBOS
time: 1.4919238919999884
current classifier in progress: HBOS
time: 0.23271063199999276
current classifier in progress: IForest
time: 18.568417248000003
current classifier in progress: KNN
current classifier in progress: LOF
current classifier in progress: MCD
time: 34.068641791000005
current classifier in progress: OCSVM
current classifier in progress: Perception
time: 0.37096926499998517
current file in progress ...: cardio
current classifier in progress: HBOS
time: 0.006678477999997767
current classifier in progress: HBOS
time: 0.0060919210000065505
current classifier in progress: IForest
time: 0.25206052300001147
current classifier in progress: KNN
time: 0.057625674999997045
current classifier in progress: LOF
time: 0.05081681199999366
current classifier in progress: MCD
time: 0.472412807000012
current classifier in progress: OCSVM
time: 0.28290890899998544
current classifier in progress: Perception
time: 0.002055848000026117
current file in progress ...: shuttle
current classifier in progress: HBOS
time: 0.013202458000023398
current classifier in progress: HBOS
time: 0.012457288000007338
current classifier in progress: IForest
time: 2.383925222000016
current classifier in progress: KNN
time: 4.01472331399998
current classifier in progress: LOF
time: 8.107811593999998
current classifier in progress: MCD
time: 14.938943524999985
current classifier in progress: OCSVM
time: 197.24415067100003
current classifier in progress: Perception
time: 0.04409405599994898
current file in progress ...: musk
current classifier in progress: HBOS
time: 0.04331530000001749
current classifier in progress: HBOS
time: 0.04250869700001658
current classifier in progress: IForest
time: 0.6932891950000339
current classifier in progress: KNN
time: 0.1748345400000062
current classifier in progress: LOF
time: 0.141486953000026
current classifier in progress: MCD
time: 7.155057929999998
current classifier in progress: OCSVM
time: 1.023312601999919
current classifier in progress: Perception
time: 0.008825023999975201
current file in progress ...: http
current classifier in progress: HBOS
time: 0.056875523000030626
current classifier in progress: HBOS
time: 0.06478884699993159
current classifier in progress: IForest
time: 23.317903814000033
current classifier in progress: KNN
time: 7.891814101999898
current classifier in progress: LOF
time: 10.48716510700001
current classifier in progress: MCD
time: 41.32176340800004
current classifier in progress: OCSVM
current classifier in progress: Perception
time: 0.5074690389999432
current file in progress ...: smtp
current classifier in progress: HBOS
time: 0.01242759699994167
current classifier in progress: HBOS
time: 0.017870991999984653
current classifier in progress: IForest
time: 4.391381403999958
current classifier in progress: KNN
time: 0.5170946599999979
current classifier in progress: LOF
time: 0.8628221929999427
current classifier in progress: MCD
time: 15.811476540000058
current classifier in progress: OCSVM
time: 775.9217492540001
current classifier in progress: Perception
time: 0.08405737600014618
current file in progress ...: thyroid
current classifier in progress: HBOS
time: 0.0029107420000400452
current classifier in progress: HBOS
time: 0.0025409580002815346
current classifier in progress: IForest
time: 0.3856201290000172
current classifier in progress: KNN
time: 0.05172284399986893
current classifier in progress: LOF
time: 0.09420475500019165
current classifier in progress: MCD
time: 1.0648482669998884
current classifier in progress: OCSVM
time: 0.936213048999889
current classifier in progress: Perception
time: 0.0034938819999297266
current file in progress ...: wbc
current classifier in progress: HBOS
time: 0.006390350999936345
current classifier in progress: HBOS
time: 0.006290746000104264
current classifier in progress: IForest
time: 0.15857725299974845
current classifier in progress: KNN
time: 0.0028420140001799155
current classifier in progress: LOF
time: 0.006552062999617192
current classifier in progress: MCD
time: 0.14265156200008278
current classifier in progress: OCSVM
time: 0.011651811999854544
current classifier in progress: Perception
time: 0.0012388329996610992
current file in progress ...: satimage-2
current classifier in progress: HBOS
time: 0.032703465999929904
current classifier in progress: HBOS
time: 0.01437451299989334
current classifier in progress: IForest
time: 0.6192121320000297
current classifier in progress: KNN
time: 0.6150044190003428
current classifier in progress: LOF
time: 0.47861787300007563
current classifier in progress: MCD
time: 2.497732987999825
current classifier in progress: OCSVM
time: 3.201814838000246
current classifier in progress: Perception
time: 0.006901388999722258

In [5]:
# create dataframe for precision
df_precision = metrics_df[['Dataset', 'Classifier', 'Precision']]
df_precision = pd.pivot_table(df_precision, values = 'Precision', index=['Classifier'], columns='Dataset').reset_index()
df_precision.columns.name = None

cols = [col for col in df_precision.columns]
formatdict = {}
for col in cols: formatdict[col] = "{:.3f}"
formatdict.pop('Classifier', None)

sub = df_precision.columns.values.tolist()
sub.remove('Classifier')
sub

df_precision = df_precision.style.hide_index().apply(highlight_max, subset=sub).format(formatdict)

# img_title = "Precision results"
# path_save = image_save_path + "dataset_precision.png"

# dfi.export(df_precision,path_save)

df_precision

In [6]:
# create dataframe for recall
df_recall = metrics_df[['Dataset', 'Classifier', 'Recall']]
df_recall = pd.pivot_table(df_recall, values = 'Recall', index=['Classifier'], columns='Dataset').reset_index()
df_recall.columns.name = None

cols = [col for col in df_recall.columns]
formatdict = {}
for col in cols: formatdict[col] = "{:.2f}"
formatdict.pop('Classifier', None)

sub = df_recall.columns.values.tolist()
sub.remove('Classifier')
sub

df_recall = df_recall.style.hide_index().apply(highlight_max, subset=sub).format(formatdict)

img_title = "Recall results"
path_save = image_save_path + "dataset_recall.png"

# dfi.export(df_recall,path_save)

df_recall

In [7]:
# create dataframe for F1-score
df_f1= metrics_df[['Dataset', 'Classifier', 'F1']]
df_f1 = pd.pivot_table(df_f1, values = 'F1', index=['Classifier'], columns='Dataset').reset_index()
df_f1.columns.name = None

cols = [col for col in df_f1.columns]
formatdict = {}
for col in cols: formatdict[col] = "{:.3f}"
formatdict.pop('Classifier', None)

sub = df_f1.columns.values.tolist()
sub.remove('Classifier')
sub

df_f1 = df_f1.style.hide_index().apply(highlight_max, subset=sub).format(formatdict)

img_title = "F1-score results"
path_save = image_save_path + "dataset_f1-score.png"

# dfi.export(df_f1,path_save)

df_f1

In [8]:
# create dataframe for Area under ROC curve
df1= metrics_df[['Dataset', 'Classifier', 'AUC']]
df1 = pd.pivot_table(df1, values = 'AUC', index=['Classifier'], columns='Dataset').reset_index()
df1.columns.name = None

cols = [col for col in df1.columns]
formatdict = {}
for col in cols: formatdict[col] = "{:.2f}"
formatdict.pop('Classifier', None)

sub = df1.columns.values.tolist()
sub.remove('Classifier')
sub

df1 = df1.style.hide_index().apply(highlight_max, subset=sub).format(formatdict)

img_title = "F1-score results"
path_save = image_save_path + "dataset_auc.png"

# dfi.export(df1,path_save)

df1

In [9]:
# create dataframe for total training and prediction time
df1= metrics_df[['Dataset', 'Classifier', 'Runtime']]
df1 = pd.pivot_table(df1, values = 'Runtime', index=['Classifier'], columns='Dataset').reset_index()
df1.columns.name = None

cols = [col for col in df1.columns]
formatdict = {}
for col in cols: formatdict[col] = "{:.4f}"
formatdict.pop('Classifier', None)

sub = df1.columns.values.tolist()
sub.remove('Classifier')
sub

df1 = df1.style.hide_index().apply(highlight_min, subset=sub).format(formatdict)

path_save = image_save_path + "dataset_total_time.png"

# dfi.export(df1,path_save)

df1